##Numpy array and basics

In [9]:
import numpy as np

##creating array from list

In [10]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : ", arr_2d)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


##List vs numpy array

In [21]:
py_list = [1,2,3]
print("Python list multiply : ", py_list*2)

np_array = np.array([1,2,3]) #element wise multillication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time()- start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy  operation time : ", time.time()- start)


Python list multiply :  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time :  0.08373904228210449

 Numpy  operation time :  0.0071790218353271484


##crating array from scratch

In [27]:
zeros = np.zeros((3,4))
print("Zeros array : \n", zeros)

ones = np.ones((2,3))
print("Ones array : \n", ones)

full = np.full((2,2), 6)
print("Full array : \n", full)

random = np.random.random((2,3))
print("Random array : \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array : \n", sequence)


Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array : 
 [[6 6]
 [6 6]]
Random array : 
 [[0.51791514 0.77539823 0.03562275]
 [0.45840318 0.58226468 0.72377308]]
Sequence array : 
 [0 2 4 6 8]


##Vector, Matrix and Tensor

In [29]:
vector = np.array([1,2,3])
print("Vector : ", vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("Matrix : ", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor : ", tensor)




Vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##Array properties

In [33]:
arr = np.array([[1, 2,3], [4,5,6]])
print("Shape ",arr.shape)
print("Dimention ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimention  2
Size  6
DType  int64


In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : ", arr_1d)